# -*- coding: utf-8 -*-
"""PNCT Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G11wwKq6sDaICxVNAzkl_R0VhNUvm75o
"""

pip install phonenumbers

import phonenumbers
from phonenumbers import geocoder, parse

phone_number1 = parse("+1 (623) 450-4918")
phone_number2 = parse("+1 (562) 715-6549")
phone_number3 = parse("+1 (239) 436-6271")

print("Phone Numbers Location:")
print(geocoder.description_for_number(phone_number1, "en"))
print(geocoder.description_for_number(phone_number2, "en"))
print(geocoder.description_for_number(phone_number3, "en"))